<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Contact\Block\ContactForm $block */
?>
<form class="form question"
      action="<?= $block->escapeUrl($block->getFormAction()) ?>"
      id="question-form"
      method="post"
      data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
      data-mage-init='{"validation":{}}'>
    <fieldset class="fieldset">
        <div class="field name required">
            <label class="label" for="name"><span><?= $block->escapeHtml(__('Имя')) ?></span></label>
            <div class="control">
                <input name="name" id="name" title="<?= $block->escapeHtmlAttr(__('Имя')) ?>" value="<?= $block->escapeHtmlAttr($this->helper(\Astrio\TrainingQuestion\Helper\Data::class)->getPostValue('name') )?>" class="input-text" type="text" data-validate="{required:true}"/>
            </div>
        </div>
        <div class="field question required">
            <label class="label" for="question"><span><?= $block->escapeHtml(__('Введите вопрос')) ?></span></label>
            <div class="control">
                <textarea name="content" id="content" title="<?= $block->escapeHtmlAttr(__('Введите вопрос')) ?>" class="input-text" cols="5" rows="3" data-validate="{required:true}">
                    <?= $block->escapeHtml($this->helper(\Astrio\TrainingQuestion\Helper\Data::class)->getPostValue('content')) ?>
                </textarea>
            </div>
        </div>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <input type="hidden" name="hideit" id="hideit" value="" />
            <button type="submit" title="<?= $block->escapeHtmlAttr(__('Submit')) ?>" class="action submit primary">
                <span><?= $block->escapeHtml(__('Submit')) ?></span>
            </button>
        </div>
    </div>
</form>
